// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proxy/vless/inbound/unknown_user.proto

package inbound

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnknownUserAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteIp      string                 `protobuf:"bytes,1,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	RemotePort    int32                  `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	AttemptedUuid string                 `protobuf:"bytes,3,opt,name=attempted_uuid,json=attemptedUuid,proto3" json:"attempted_uuid,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownUserAttempt) Reset() {
	*x = UnknownUserAttempt{}
	mi := &file_proxy_vless_inbound_unknown_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownUserAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownUserAttempt) ProtoMessage() {}

func (x *UnknownUserAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_inbound_unknown_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownUserAttempt.ProtoReflect.Descriptor instead.
func (*UnknownUserAttempt) Descriptor() ([]byte, []int) {
	return file_proxy_vless_inbound_unknown_user_proto_rawDescGZIP(), []int{0}
}

func (x *UnknownUserAttempt) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *UnknownUserAttempt) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *UnknownUserAttempt) GetAttemptedUuid() string {
	if x != nil {
		return x.AttemptedUuid
	}
	return ""
}

func (x *UnknownUserAttempt) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proxy_vless_inbound_unknown_user_proto protoreflect.FileDescriptor

const file_proxy_vless_inbound_unknown_user_proto_rawDesc = "" +
	"\n" +
	"&proxy/vless/inbound/unknown_user.proto\x12\x18xray.proxy.vless.inbound\"\x97\x01\n" +
	"\x12UnknownUserAttempt\x12\x1b\n" +
	"\tremote_ip\x18\x01 \x01(\tR\bremoteIp\x12\x1f\n" +
	"\vremote_port\x18\x02 \x01(\x05R\n" +
	"remotePort\x12%\n" +
	"\x0eattempted_uuid\x18\x03 \x01(\tR\rattemptedUuid\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampBy\n" +
	"\x1ccom.xray.proxy.vless.inboundP\x01Z<github.com/amnezia-vpn/amnezia-xray-core/proxy/vless/inbound\xaa\x02\x18Xray.Proxy.Vless.Inboundb\x06proto3"

var (
	file_proxy_vless_inbound_unknown_user_proto_rawDescOnce sync.Once
	file_proxy_vless_inbound_unknown_user_proto_rawDescData []byte
)

func file_proxy_vless_inbound_unknown_user_proto_rawDescGZIP() []byte {
	file_proxy_vless_inbound_unknown_user_proto_rawDescOnce.Do(func() {
		file_proxy_vless_inbound_unknown_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_vless_inbound_unknown_user_proto_rawDesc), len(file_proxy_vless_inbound_unknown_user_proto_rawDesc)))
	})
	return file_proxy_vless_inbound_unknown_user_proto_rawDescData
}

var file_proxy_vless_inbound_unknown_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_vless_inbound_unknown_user_proto_goTypes = []any{
	(*UnknownUserAttempt)(nil), // 0: xray.proxy.vless.inbound.UnknownUserAttempt
}
var file_proxy_vless_inbound_unknown_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_vless_inbound_unknown_user_proto_init() }
func file_proxy_vless_inbound_unknown_user_proto_init() {
	if File_proxy_vless_inbound_unknown_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_vless_inbound_unknown_user_proto_rawDesc), len(file_proxy_vless_inbound_unknown_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_vless_inbound_unknown_user_proto_goTypes,
		DependencyIndexes: file_proxy_vless_inbound_unknown_user_proto_depIdxs,
		MessageInfos:      file_proxy_vless_inbound_unknown_user_proto_msgTypes,
	}.Build()
	File_proxy_vless_inbound_unknown_user_proto = out.File
	file_proxy_vless_inbound_unknown_user_proto_goTypes = nil
	file_proxy_vless_inbound_unknown_user_proto_depIdxs = nil
}
